import { Capa } from '../interfaces/capas.interface';
import { styleLine } from './style-line';
import { stylePoint } from './style-point';
import { stylePolygon } from './style-polygon';

export const capasCatastroMinero: Capa[] = [
  {
    tabla: 'canteras',
    geometria: { db: 'geom', shapefile: 'geometry' },
    propiedades: [
      { db: 'expediente', shapefile: 'expediente' },
      { db: 'titular', shapefile: 'titular' },
      { db: 'nombre', shapefile: 'nombre' },
      { db: 'mineral', shapefile: 'mineral' },
      { db: 'categoria', shapefile: 'categoria' },
      { db: 'superficie', shapefile: 'superficie' },
    ],
    retorna: 'id',
    style: stylePolygon,
  },
  {
    tabla: 'cateos',
    geometria: { db: 'geom', shapefile: 'geometry' },
    propiedades: [
      { db: 'expediente', shapefile: 'expediente' },
      { db: 'titular', shapefile: 'titular' },
      { db: 'nombre', shapefile: 'nombre' },
      { db: 'superficie', shapefile: 'superficie' },
    ],
    retorna: 'id',
    style: stylePolygon,
  },
  {
    tabla: 'demasias',
    geometria: { db: 'geom', shapefile: 'geometry' },
    propiedades: [
      { db: 'expediente', shapefile: 'expediente' },
      { db: 'titular', shapefile: 'titular' },
      { db: 'nombre', shapefile: 'nombre' },
      { db: 'mineral', shapefile: 'mineral' },
      { db: 'categoria', shapefile: 'categoria' },
      { db: 'superficie', shapefile: 'superficie' },
    ],
    retorna: 'id',
    style: stylePolygon,
  },
  {
    tabla: 'manifestaciones',
    geometria: { db: 'geom', shapefile: 'geometry' },
    propiedades: [
      { db: 'expediente', shapefile: 'expediente' },
      { db: 'titular', shapefile: 'titular' },
      { db: 'nombre', shapefile: 'nombre' },
      { db: 'mineral', shapefile: 'mineral' },
      { db: 'categoria', shapefile: 'categoria' },
      { db: 'superficie', shapefile: 'superficie' },
    ],
    retorna: 'id',
    style: stylePolygon,
  },
  {
    tabla: 'minas',
    geometria: { db: 'geom', shapefile: 'geometry' },
    propiedades: [
      { db: 'expediente', shapefile: 'expediente' },
      { db: 'titular', shapefile: 'titular' },
      { db: 'nombre', shapefile: 'nombre' },
      { db: 'mineral', shapefile: 'mineral' },
      { db: 'categoria', shapefile: 'categoria' },
      { db: 'superficie', shapefile: 'superficie' },
    ],
    retorna: 'id',
    style: stylePolygon,
  },
  {
    tabla: 'registro_de_acopios',
    geometria: { db: 'geom', shapefile: 'geometry' },
    propiedades: [
      { db: 'expediente', shapefile: 'EXPTE' },
      { db: 'acopio', shapefile: 'NRO_ACOPIO' },
      { db: 'empresa', shapefile: 'EMPRESA' },
      { db: 'prop_repr', shapefile: 'PROP_REPR' },
      { db: 'domicilio', shapefile: 'DOMICILIO' },
      { db: 'dni', shapefile: 'DNI' },
      { db: 'ubicacion', shapefile: 'UBICACION_' },
      { db: 'localidad', shapefile: 'LOCALIDAD' },
      { db: 'c_p', shapefile: 'C_P' },
      { db: 'tel_fax', shapefile: 'TEL_FAX' },
      { db: 'e_mail', shapefile: 'E_MAIL' },
      { db: 'yac_provee', shapefile: 'YAC_PROVEE' },
      { db: 'mineral', shapefile: 'MINERAL' },
    ],
    retorna: 'id',
    style: stylePoint,
  },
  {
    tabla: 'registro_de_plantas',
    geometria: { db: 'geom', shapefile: 'geometry' },
    propiedades: [
      { db: 'expediente', shapefile: 'nº expte' },
      { db: 'empresa', shapefile: 'empresa' },
      { db: 'titular', shapefile: 'titular' },
      { db: 'apoderado', shapefile: 'apoderado/' },
      { db: 'tipo_de_pl', shapefile: 'tipo de pl' },
      { db: 'materia_pr', shapefile: 'materia pr' },
      { db: 'proceso_de', shapefile: 'proceso de' },
      { db: 'producto_f', shapefile: 'producto f' },
      { db: 'yacimiento', shapefile: 'yacimiento' },
      { db: 'personal', shapefile: 'personal' },
      { db: 'porc_empleo_l', shapefile: '% empleo l' },
      { db: 'inversiones', shapefile: 'inversione' },
      { db: 'instalacion', shapefile: 'instalacio' },
      { db: 'volumen_de', shapefile: 'volumen de' },
      { db: 'promedio_m', shapefile: 'promedio m' },
      { db: 'comerciali', shapefile: 'comerciali' },
      { db: 'exportacion', shapefile: 'exportacio' },
      { db: 'domicilio', shapefile: 'domicilio' },
      { db: 'tel_fax', shapefile: 'tel/fax' },
      { db: 'email', shapefile: 'email' },
      { db: 'dja', shapefile: 'dja' },
      { db: 'fecha_de_p', shapefile: 'fecha de p' },
      { db: 'sellado_de', shapefile: 'sellado de' },
      { db: 'observaciones', shapefile: 'observacio' },
    ],
    retorna: 'id',
    style: stylePoint,
  },
  {
    tabla: 'servidumbres_de_ocupacion',
    geometria: { db: 'geom', shapefile: 'geometry' },
    propiedades: [
      { db: 'expediente', shapefile: 'EXPEDIENTE' },
      { db: 'titular', shapefile: 'TITULAR' },
      { db: 'superficie', shapefile: 'SUPERFICIE' },
    ],
    retorna: 'id',
    style: stylePolygon,
  },
  {
    tabla: 'servidumbres_de_paso',
    geometria: { db: 'geom', shapefile: 'geometry' },
    propiedades: [
      { db: 'expediente', shapefile: 'EXPEDIENTE' },
      { db: 'titular', shapefile: 'TITULAR' },
      { db: 'long_m', shapefile: 'LONG (M)' },
    ],
    retorna: 'id',
    style: styleLine,
  },
  {
    tabla: 'vacantes',
    geometria: { db: 'geom', shapefile: 'geometry' },
    propiedades: [
      { db: 'expediente', shapefile: 'expediente' },
      { db: 'titular', shapefile: 'titular' },
      { db: 'nombre', shapefile: 'nombre' },
      { db: 'mineral', shapefile: 'mineral' },
      { db: 'categoria', shapefile: 'categoria' },
      { db: 'superficie', shapefile: 'superficie' },
    ],
    retorna: 'id',
    style: stylePolygon,
  },
];
